server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service #路由标识，唯一
          uri: lb://userservice #路由的目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #判断是否以user开头

        - id: news-service
          uri: lb://newsservice
          predicates:
            - Path=/news/**
      default-filters:
        - AddRequestHeader=Truth, hello world!

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
